/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nd;

import database_test.Menu;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author ohkoo
 * 
 * 
 */
public class reEnterMain extends javax.swing.JFrame {
    String[] arr = {"นาย","นาง","นางสาว"};
    static String text ;
    static reEnterMain rem = new reEnterMain();
    /**
     * Creates new form reEnterMain
     */
    public reEnterMain() {
        initComponents();
        setCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        p_pre_name = new javax.swing.JComboBox<>();
        p_fname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        p_lname = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        HN = new javax.swing.JLabel();
        hn = new javax.swing.JTextField();
        Date_today = new com.toedter.calendar.JDateChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Jtabbed1 = new javax.swing.JPanel();
        Part1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        id_num = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        p_nation = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        job = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        p_tel = new javax.swing.JFormattedTextField();
        birth_date = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        t_birth_date = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        main_element = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        sub_element = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        p_gender1 = new javax.swing.JRadioButton();
        p_gender2 = new javax.swing.JRadioButton();
        p_gender3 = new javax.swing.JRadioButton();
        p_religion = new javax.swing.JComboBox<>();
        Part2 = new javax.swing.JPanel();
        Soi = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        Road = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        name_th = new javax.swing.JComboBox<>();
        jLabel53 = new javax.swing.JLabel();
        d_name_th = new javax.swing.JComboBox<>();
        jLabel60 = new javax.swing.JLabel();
        sd_code = new javax.swing.JComboBox<>();
        jLabel61 = new javax.swing.JLabel();
        zip_code = new javax.swing.JTextField();
        Moo = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        Part3 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        r_nation = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        p_status1 = new javax.swing.JRadioButton();
        p_status2 = new javax.swing.JRadioButton();
        p_status3 = new javax.swing.JRadioButton();
        p_status4 = new javax.swing.JRadioButton();
        p_status5 = new javax.swing.JRadioButton();
        H_tel = new javax.swing.JFormattedTextField();
        rr_tel = new javax.swing.JFormattedTextField();
        Part4 = new javax.swing.JPanel();
        r_fname = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        r_lname = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        r_status = new javax.swing.JTextField();
        r_tel = new javax.swing.JFormattedTextField();
        Jtabbed2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        hist_live = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        hist_ill = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        Jtabbed3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        height = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SYS = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pulse = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Vital = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tempC = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        BMI = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        med_allergic = new javax.swing.JTextField();
        food_allergic = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        hist_illF = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton2");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(195, 195, 247));
        jPanel1.setPreferredSize(new java.awt.Dimension(1288, 91));

        headerPanel.setBackground(new java.awt.Color(195, 195, 247));
        headerPanel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jLabel5.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel5.setText("คำนำหน้าชื่อ");
        headerPanel.add(jLabel5);

        p_pre_name.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        p_pre_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_pre_nameActionPerformed(evt);
            }
        });
        headerPanel.add(p_pre_name);

        p_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_fnameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel2.setText("ชื่อ");

        jLabel3.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel3.setText("นามสกุล");

        p_lname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                p_lnameInputMethodTextChanged(evt);
            }
        });
        p_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_lnameActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel32.setText("วันที่ :");

        HN.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        HN.setText("เลขHN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(HN)
                        .addGap(18, 18, 18)
                        .addComponent(hn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25)
                        .addComponent(p_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Date_today, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(596, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Date_today, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(p_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        Jtabbed1.setLayout(null);

        Part1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel4.setText("เลขบัตรประชาชน ");

        id_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_numActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel17.setText("สัญชาติ");

        jLabel16.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel16.setText("เบอร์โทรติดต่อ");

        p_nation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_nationActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel10.setText("วัน/เดือน/ปี เกิด");

        jLabel33.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel33.setText("อาชีพ");

        job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel19.setText("เพศ");

        jLabel34.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel34.setText("ศาสนา");

        try {
            p_tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        birth_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birth_dateActionPerformed(evt);
            }
        });

        jButton7.setText("...");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel31.setText("วัน/เดือน/ปี เกิด ไทย");

        t_birth_date.setPreferredSize(new java.awt.Dimension(72, 22));
        t_birth_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_birth_dateActionPerformed(evt);
            }
        });

        jButton8.setText("...");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel35.setText("ธาตุเจ้าเรือนหลัก");

        main_element.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N

        jLabel45.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel45.setText("ธาตุเจ้าเรือนรอง");

        sub_element.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        sub_element.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_elementActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        buttonGroup1.add(p_gender1);
        p_gender1.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        p_gender1.setText("ชาย");
        jPanel3.add(p_gender1);

        buttonGroup1.add(p_gender2);
        p_gender2.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        p_gender2.setText("หญิง");
        p_gender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_gender2ActionPerformed(evt);
            }
        });
        jPanel3.add(p_gender2);

        buttonGroup1.add(p_gender3);
        p_gender3.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        p_gender3.setText("อื่นๆ");
        p_gender3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_gender3ActionPerformed(evt);
            }
        });
        jPanel3.add(p_gender3);

        p_religion.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N

        javax.swing.GroupLayout Part1Layout = new javax.swing.GroupLayout(Part1);
        Part1.setLayout(Part1Layout);
        Part1Layout.setHorizontalGroup(
            Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Part1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Part1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addComponent(id_num)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(birth_date, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(job)
                        .addGap(431, 431, 431))
                    .addGroup(Part1Layout.createSequentialGroup()
                        .addGroup(Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Part1Layout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_birth_date, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(main_element, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sub_element, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Part1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p_nation, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p_religion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(617, 617, 617))))
        );
        Part1Layout.setVerticalGroup(
            Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Part1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(id_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(birth_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jLabel33)
                    .addComponent(job, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p_religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(p_nation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(p_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))))
                    .addComponent(jLabel34))
                .addGap(16, 16, 16)
                .addGroup(Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(t_birth_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(jLabel35)
                    .addComponent(main_element, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45)
                    .addComponent(sub_element, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jtabbed1.add(Part1);
        Part1.setBounds(2, 0, 1260, 130);

        Part2.setPreferredSize(new java.awt.Dimension(1333, 120));

        Soi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoiActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel46.setText("ซอย");

        Road.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoadActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel51.setText("ถนน");

        jLabel52.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel52.setText("จังหวัด");

        name_th.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        name_th.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel53.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel53.setText("อำเภอ/เขต");

        d_name_th.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        d_name_th.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel60.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel60.setText("ตำบล/แขวง");

        sd_code.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        sd_code.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel61.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel61.setText("รหัสไปรษณีย์");

        zip_code.setEditable(false);
        zip_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zip_codeActionPerformed(evt);
            }
        });

        Moo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MooActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel39.setText("หมู่");

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel40.setText("ที่อยู่ปัจจุบัน");

        javax.swing.GroupLayout Part2Layout = new javax.swing.GroupLayout(Part2);
        Part2.setLayout(Part2Layout);
        Part2Layout.setHorizontalGroup(
            Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Part2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Part2Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Moo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Part2Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Soi, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Road, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name_th, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Part2Layout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addGap(18, 18, 18)
                        .addComponent(d_name_th, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel60)
                        .addGap(18, 18, 18)
                        .addComponent(sd_code, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel61)
                        .addGap(18, 18, 18)
                        .addComponent(zip_code, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Part2Layout.setVerticalGroup(
            Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Part2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(Moo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(Soi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51)
                    .addComponent(Road, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(name_th, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel60)
                        .addComponent(sd_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel61)
                        .addComponent(zip_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel53)
                        .addComponent(d_name_th, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Jtabbed1.add(Part2);
        Part2.setBounds(0, 130, 1260, 120);

        jLabel42.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel42.setText("โทรศัพท์บ้าน");

        jLabel43.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel43.setText("มือถือ");

        jLabel44.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel44.setText("สถานภาพสมรส");

        jLabel63.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel63.setText("สัญชาติ");

        r_nation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_nationActionPerformed(evt);
            }
        });

        jPanel12.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        buttonGroup2.add(p_status1);
        p_status1.setText("สมรส");
        jPanel12.add(p_status1);

        buttonGroup2.add(p_status2);
        p_status2.setText("หม้าย");
        jPanel12.add(p_status2);

        buttonGroup2.add(p_status3);
        p_status3.setText("หย่า");
        jPanel12.add(p_status3);

        buttonGroup2.add(p_status4);
        p_status4.setText("แยกกันอยู่");
        jPanel12.add(p_status4);

        buttonGroup2.add(p_status5);
        p_status5.setText("โสด ");
        jPanel12.add(p_status5);

        try {
            H_tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            rr_tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout Part3Layout = new javax.swing.GroupLayout(Part3);
        Part3.setLayout(Part3Layout);
        Part3Layout.setHorizontalGroup(
            Part3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Part3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(Part3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Part3Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addComponent(H_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rr_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Part3Layout.createSequentialGroup()
                        .addComponent(jLabel63)
                        .addGap(18, 18, 18)
                        .addComponent(r_nation, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel44)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Part3Layout.setVerticalGroup(
            Part3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Part3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Part3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(H_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rr_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Part3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Part3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel44)
                        .addComponent(jLabel63)
                        .addComponent(r_nation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jtabbed1.add(Part3);
        Part3.setBounds(0, 250, 1260, 103);

        r_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_fnameActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel36.setText("ชื่อผู้ติดต่อ");

        jLabel37.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel37.setText("นามสกุลผู้ติดต่อ");

        jLabel41.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel41.setText("ความเกี่ยวข้อง");

        jLabel62.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel62.setText("เบอร์โทรศัพท์ผู้ติดต่อ");

        r_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_lnameActionPerformed(evt);
            }
        });

        jPanel11.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        r_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_statusActionPerformed(evt);
            }
        });

        try {
            r_tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout Part4Layout = new javax.swing.GroupLayout(Part4);
        Part4.setLayout(Part4Layout);
        Part4Layout.setHorizontalGroup(
            Part4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Part4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(Part4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Part4Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addComponent(r_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Part4Layout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel41)
                        .addGap(18, 18, 18)
                        .addComponent(r_status, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Part4Layout.setVerticalGroup(
            Part4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Part4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Part4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(r_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(r_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Part4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Part4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel41)
                        .addComponent(jLabel62)
                        .addComponent(r_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jtabbed1.add(Part4);
        Part4.setBounds(0, 340, 1260, 100);

        jTabbedPane1.addTab("ข้อมูลทั่วไป", Jtabbed1);

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel28.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel28.setText("ประวัติการเจ็บป่วยในอดีต");

        jLabel29.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel29.setText("ประวัติการเจ็บป่วยในครอบครัว");

        jLabel30.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel30.setText("ประวัติส่วนตัว");

        jLabel38.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel38.setText("ประวัติประจำเดือน");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(hist_ill, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(hist_live, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel29))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel28)
                .addGap(26, 26, 26)
                .addComponent(hist_ill, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(hist_live, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel29)
                .addGap(6, 6, 6)
                .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel38)
                .addGap(6, 6, 6)
                .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout Jtabbed2Layout = new javax.swing.GroupLayout(Jtabbed2);
        Jtabbed2.setLayout(Jtabbed2Layout);
        Jtabbed2Layout.setHorizontalGroup(
            Jtabbed2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        Jtabbed2Layout.setVerticalGroup(
            Jtabbed2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jtabbed2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ประวัติการเจ็บป่วย", Jtabbed2);

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel1.setText("น้ำหนัก :");

        jLabel11.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel11.setText("ส่วนสูง :");

        jLabel12.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel12.setText("กิโลกรัม");

        jLabel13.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel13.setText("เซนติเมตร");

        jLabel14.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel14.setText("ความดัน :");

        jLabel15.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel15.setText("มิลลิเมตรปรอท");

        jLabel18.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel18.setText("ชีพจร :");

        jLabel20.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel20.setText("การหายใจ :");

        jLabel21.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel21.setText("ครั้ง/นาที");

        jLabel22.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel22.setText("อุณหภูมิ :");

        jLabel23.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel23.setText("องศาเซลเซียส");

        jLabel24.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel24.setText("BMI :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(SYS, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(pulse, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(Vital, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tempC, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BMI, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(SYS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(pulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Vital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(tempC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(BMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel25.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel25.setText("ประวัติการแพ้ยา");

        jLabel26.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel26.setText("ประวัติการแพ้อาหาร");

        jLabel27.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel27.setText("โรคประจำตัว");

        hist_illF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hist_illFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jtabbed3Layout = new javax.swing.GroupLayout(Jtabbed3);
        Jtabbed3.setLayout(Jtabbed3Layout);
        Jtabbed3Layout.setHorizontalGroup(
            Jtabbed3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jtabbed3Layout.createSequentialGroup()
                .addGroup(Jtabbed3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jtabbed3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel25)
                        .addGap(289, 289, 289))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jtabbed3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(med_allergic, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(Jtabbed3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(hist_illF, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Jtabbed3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(food_allergic, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
            .addGroup(Jtabbed3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Jtabbed3Layout.setVerticalGroup(
            Jtabbed3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jtabbed3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Jtabbed3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Jtabbed3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Jtabbed3Layout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(med_allergic, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jtabbed3Layout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(food_allergic, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Jtabbed3Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hist_illF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ข้อมูลสุขภาพ", Jtabbed3);

        buttonPanel.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        buttonPanel.add(jButton2);

        jButton3.setText("Clear");
        buttonPanel.add(jButton3);

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        buttonPanel.add(jButton4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(541, 541, 541)
                .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        text =  String.valueOf(getfirstChar());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //        System.out.print(jTextDate1.getText());\
        rem.updateValue();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void p_pre_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_pre_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_pre_nameActionPerformed

    private void p_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_fnameActionPerformed

    private void p_lnameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_p_lnameInputMethodTextChanged

    }//GEN-LAST:event_p_lnameInputMethodTextChanged

    private void p_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_lnameActionPerformed

    private void id_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_numActionPerformed

    private void p_nationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_nationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_nationActionPerformed

    private void jobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobActionPerformed

    private void birth_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birth_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birth_dateActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dateChooser2.showPopup();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void t_birth_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_birth_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_birth_dateActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dateChooser3.showPopup();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void sub_elementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_elementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_elementActionPerformed

    private void p_gender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_gender2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_gender2ActionPerformed

    private void p_gender3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_gender3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_gender3ActionPerformed

    private void SoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoiActionPerformed

    private void RoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoadActionPerformed

    private void zip_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zip_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zip_codeActionPerformed

    private void MooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MooActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void r_nationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_nationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_nationActionPerformed

    private void r_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_fnameActionPerformed

    private void r_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_lnameActionPerformed

    private void r_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_statusActionPerformed

    private void hist_illFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hist_illFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hist_illFActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
            String HN = this.hn.getText();
            String id_num = Date_Today.getText();
            String p_pre_name = Date_Today.getText();
            String p_fname = tfpassword.getText();
            String p_lname = tfusername.getText();
            String birth_date = tfpassword.getText();
            String job = tfusername.getText();
            String address = tfpassword.getText();
            String code = tfpassword.getText();
            String address = tfpassword.getText();
            String p_tel = tfpassword.getText();
            String p_nation = tfpassword.getText();
            String p_religion = tfpassword.getText();
            String p_gender = tfpassword.getText();
            String p_status = tfpassword.getText();
            String r_fname = tfpassword.getText();
            String r_lname = tfpassword.getText();
            String r_tel = tfpassword.getText();
            String r_status = tfpassword.getText();
            String t_birth_date = tfpassword.getText();
            String t_day = tfpassword.getText();
            String t_month = tfpassword.getText();
            String t_year = tfpassword.getText();
            String main_element = tfpassword.getText();
            String sub_element = tfpassword.getText();
            String weak_health = tfpassword.getText();
            String med_allergic = tfpassword.getText();
            String food_allergic = tfpassword.getText();
            String hist_ill = tfpassword.getText();
            String hist_illF = tfpassword.getText();
            String hist_live = tfpassword.getText();
            String hist_period = tfpassword.getText();            

            //ส่วนส่งข้อมูล
            pst.setString(1, HN);
            pst.setString(2, id_num);
            pst.setString(3, p_pre_name);
            pst.setString(4, p_fname);
            pst.setString(5, p_lname);
            pst.setString(6, birth_date);
            pst.setString(7, job);
            pst.setString(8, address);
            pst.setString(9, code);
            pst.setString(10, p_tel);
            pst.setString(11, p_nation);
            pst.setString(12, p_religion);
            pst.setString(13, p_gender);
            pst.setString(14, p_status);
            pst.setString(15, r_fname);
            pst.setString(16, r_lname);
            pst.setString(17, r_tel);
            pst.setString(18, r_status);
            pst.setString(19, t_birth_date);
            pst.setString(20, t_day);
            pst.setString(21, t_month);
            pst.setString(22, t_year);
            pst.setString(23, main_element);
            pst.setString(24, sub_element);
            pst.setString(25, weak_health);
            pst.setString(26, med_allergic);
            pst.setString(27, food_allergic);
            pst.setString(28, hist_ill);
            pst.setString(29, hist_illF);
            pst.setString(30, hist_live);
            pst.setString(31, hist_period);
            
             ResultSet rs1 = pst.executeQuery();
            if(rs1.next()==false)
                {
                    JOptionPane.showMessageDialog(this, "Sorry Record Not Found");
                    tfusername.setText("");
                    tfpassword.setText("");               
                }
            else
                {
                     new nd.Menu().setVisible(true);
                     setVisible(false);
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(Employee_login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reEnterMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reEnterMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reEnterMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reEnterMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reEnterMain().setVisible(true);
            }
        });
    }
    
    public char getfirstChar(){
        String a = p_lname.getText();
        char c;
//        System.out.print(a);
        return c = a.charAt(0);
    }
    
    public void updateValue(){
        String firstlet = text+"0001";
            System.out.print(firstlet);
            jLabel1.setText(firstlet);
    }
    
    public void setCombo(){ //if we have more combo box i will Optimize this ex. districtnum provience etc.
        String[] arr = {"นาย","นาง","นางสาว"};
        String[] arr2 = {"พุทธ","คริสต์","อิสลาม","พราหมณ์ฮินดู","อื่นๆ"};
        String[] arr3 = {"ธาตุไฟ","ธาตุลม","ธาตุน้ำ","ธาตุดิน"};
        for(int i=0;i<arr.length;i++){
            p_pre_name.addItem(arr[i]);
        }
        for(int i = 0 ;i<arr.length;i++){
            p_religion.addItem(arr2[i]);
        }
        for(int i = 0 ;i<arr.length;i++){
            main_element.addItem(arr3[i]);
        }
        for(int i = 0 ;i<arr.length;i++){
            sub_element.addItem(arr3[i]);
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BMI;
    private com.toedter.calendar.JDateChooser Date_today;
    private javax.swing.JLabel HN;
    private javax.swing.JFormattedTextField H_tel;
    private javax.swing.JPanel Jtabbed1;
    private javax.swing.JPanel Jtabbed2;
    private javax.swing.JPanel Jtabbed3;
    private javax.swing.JTextField Moo;
    private javax.swing.JPanel Part1;
    private javax.swing.JPanel Part2;
    private javax.swing.JPanel Part3;
    private javax.swing.JPanel Part4;
    private javax.swing.JTextField Road;
    private javax.swing.JTextField SYS;
    private javax.swing.JTextField Soi;
    private javax.swing.JTextField Vital;
    private javax.swing.JTextField address;
    private javax.swing.JTextField birth_date;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JComboBox<String> d_name_th;
    private javax.swing.JTextField food_allergic;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTextField height;
    private javax.swing.JTextField hist_ill;
    private javax.swing.JTextField hist_illF;
    private javax.swing.JTextField hist_live;
    private javax.swing.JTextField hn;
    private javax.swing.JTextField id_num;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField job;
    private javax.swing.JComboBox<String> main_element;
    private javax.swing.JTextField med_allergic;
    private javax.swing.JComboBox<String> name_th;
    private javax.swing.JTextField p_fname;
    private javax.swing.JRadioButton p_gender1;
    private javax.swing.JRadioButton p_gender2;
    private javax.swing.JRadioButton p_gender3;
    private javax.swing.JTextField p_lname;
    private javax.swing.JTextField p_nation;
    private javax.swing.JComboBox<String> p_pre_name;
    private javax.swing.JComboBox<String> p_religion;
    private javax.swing.JRadioButton p_status1;
    private javax.swing.JRadioButton p_status2;
    private javax.swing.JRadioButton p_status3;
    private javax.swing.JRadioButton p_status4;
    private javax.swing.JRadioButton p_status5;
    private javax.swing.JFormattedTextField p_tel;
    private javax.swing.JTextField pulse;
    private javax.swing.JTextField r_fname;
    private javax.swing.JTextField r_lname;
    private javax.swing.JTextField r_nation;
    private javax.swing.JTextField r_status;
    private javax.swing.JFormattedTextField r_tel;
    private javax.swing.JFormattedTextField rr_tel;
    private javax.swing.JComboBox<String> sd_code;
    private javax.swing.JComboBox<String> sub_element;
    private javax.swing.JTextField t_birth_date;
    private javax.swing.JTextField tempC;
    private javax.swing.JTextField weight;
    private javax.swing.JTextField zip_code;
    // End of variables declaration//GEN-END:variables
}
